FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY index.html /usr/share/nginx/html/index.html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
HEALTHCHECK CMD wget -qO- http://localhost/health || exit 1

