version: '3.8'

services:
  # Infrastructure Services
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: retailai
      POSTGRES_USER: retailai
      POSTGRES_PASSWORD: retailai123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/init-db.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # API Gateway (Node.js - lighter than Python ML services)
  api-gateway:
    build: 
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://retailai:retailai123@postgres:5432/retailai
      REDIS_URL: redis://redis:6379
      JWT_SECRET: demo-jwt-secret-key
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    driver: bridge