apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retailai-data-pvc
  namespace: retailai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retailai-logs-pvc
  namespace: retailai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
